version: "3.8"

services:

  mariadb:
    image: mariadb
    container_name: mariadb_c
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    env_file:
      - ./.env
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
  
  nginx:
    image: nginx
    container_name: nginx_c
    build: requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress_c
    build: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always

# ----------- volumes --------------
volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/afenzl/data/mariadb_v
      type: none
      o: bind
  
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/afenzl/data/wordpress_v
      type: none
      o: bind


# ------------- network ------------
networks:
  inception:
    driver: bridge

