version: "3.8"

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
  
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:9000
    restart: always

    # or should restart be on_failure

# ----------- volumes --------------
volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/user42/data/mariadb_v
      type: none
      o: bind
  wp_data:
    driver: local
    driver_opts:
      device: /home/user42/data/wordpress_v
      type: none
      o: bind


# ------------- network ------------
networks:
  inception:
    driver: bridge

